# Generated by Django 5.0.6 on 2024-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InvoicePage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="invoices",
            field=models.JSONField(null=True),
        ),
    ]
