# Generated by Django 5.0.6 on 2024-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InvoicePage", "0002_customuser_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bankDetail",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phoneNumber",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sortCode",
            field=models.JSONField(null=True),
        ),
    ]
