# Generated by Django 5.0.6 on 2024-06-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InvoicePage", "0003_customuser_address_customuser_bankdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="invoices",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
